'index':
    controller: IndexController
'home':
    controller: IndexController
    function: UserHomepage


# **************************************************
# Pages - Public pages
# **************************************************
'login':
    directory: pages/public
    controller: LoggedOutPagesController
    function: Login
'sign-up':
    directory: pages/public
    controller: LoggedOutPagesController
    function: Signup



# **************************************************
# API - Public pages
# **************************************************
'action/login':
    directory: api/public
    controller: LoggedOutActionController
    function: Login
'action/logout':
    directory: api/public
    controller: LoggedOutActionController
    function: Logout
'action/signup':
    directory: api/public
    controller: LoggedOutActionController
    function: Signup



# **************************************************
# Pages - Admin pages
# **************************************************
'admin':
    directory: pages/admin
    controller: AccessPageController
    function: Home
'admin/login':
    directory: pages/admin
    controller: AccessPageController
    function: Login



'admin/account/password':
    directory: pages/admin
    controller: AccountPageController
    function: ChangePassword


'admin/batch':
    directory: pages/admin
    controller: BatchPageController
    function: Batch
'admin/batch/details':
    directory: pages/admin
    controller: BatchPageController
    function: BatchDetails
    parameter: number
'admin/batch/details/(:num)':
    directory: pages/admin
    controller: BatchPageController
    function: BatchCommitteeDetails
    parent: number
    parameter: any


'admin/member':
    directory: pages/admin
    controller: MemberPageController
    function: Member
'admin/member/details/':
    directory: pages/admin
    controller: MemberPageController
    function: MemberDetails
    parameter: number



# **************************************************
# API - Admin pages
# **************************************************
'action/admin/login':
    directory: api/admin
    controller: AccessActionController
    function: Login
'action/admin/logout':
    directory: api/admin
    controller: AccessActionController
    function: Logout



'action/admin/account/password/change':
    directory: api/admin
    controller: AccountActionController
    function: ChangePassword


'action/admin/batch':
    directory: api/admin
    controller: BatchActionController
    function: GetBatches
'action/admin/batch/add':
    directory: api/admin
    controller: BatchActionController
    function: AddBatch
'action/admin/batch/activate':
    directory: api/admin
    controller: BatchActionController
    function: ActivateBatch
'action/admin/batch/delete':
    directory: api/admin
    controller: BatchActionController
    function: DeleteBatch
'action/admin/batch/details':
    directory: api/admin
    controller: BatchActionController
    function: GetBatchDetails
    parameter: number
'action/admin/batch/details/add':
    directory: api/admin
    controller: BatchActionController
    function: AddBatchMember
    parameter: number
'action/admin/batch/details/remove':
    directory: api/admin
    controller: BatchActionController
    function: RemoveMemberFromBatch
    parameter: number
'action/admin/batch/details/(:num)':
    directory: api/admin
    controller: BatchActionController
    function: GetBatchCommitteeDetails
    parent: number
    parameter: any
'action/admin/batch/details/(:num)/modify/frontman':
    directory: api/admin
    controller: BatchActionController
    function: ModifyFrontmen
    parent: number
'action/admin/batch/details/(:num)/add/member/':
    directory: api/admin
    controller: BatchActionController
    function: AddBatchCommitteeMember
    parent: number
    parameter: any
'action/admin/batch/details/(:num)/remove/member/':
    directory: api/admin
    controller: BatchActionController
    function: RemoveBatchCommitteeMember
    parent: number
    parameter: any
'action/admin/batch/details/(:num)/make-committee-head/':
    directory: api/admin
    controller: BatchActionController
    function: UpdateBatchCommitteeHead
    parent: number
    parameter: any


'action/admin/member':
    directory: api/admin
    controller: MemberActionController
    function: GetMembers
'action/admin/member/delete':
    directory: api/admin
    controller: MemberActionController
    function: DeleteMember
'action/admin/member/details':
    directory: api/admin
    controller: MemberActionController
    function: GetMemberDetails
    parameter: number
'action/admin/member/details/modify':
    directory: api/admin
    controller: MemberActionController
    function: ModifyMemberDetails
    parameter: number



# **************************************************
# Pages - User pages
# **************************************************
'request':
    directory: pages/user
    controller: RequestPageController
    function: RequestIndex
    parameter: any


'task':
    directory: pages/user
    controller: TaskPageController
    function: TaskIndex
'task/view':
    directory: pages/user
    controller: TaskPageController
    function: ViewTaskListPage
'task/view/details':
    directory: pages/user
    controller: TaskPageController
    function: ViewTaskDetailsPage
    parameter: number
'task/add':
    directory: pages/user
    controller: TaskPageController
    function: AddTasksPage


'availability':
    directory: pages/user
    controller: AvailabilityPageController
    function: AvailabilityIndex
'availability/manage':
    directory: pages/user
    controller: AvailabilityPageController
    function: ModifyAvailability
'availability/committee':
    directory: pages/user
    controller: AvailabilityPageController
    function: CommitteeAvailability
'availability/group':
    directory: pages/user
    controller: AvailabilityPageController
    function: GroupAvailability
'availability/group/view':
    directory: pages/user
    controller: AvailabilityPageController
    function: GroupAvailabilityViewPage
    parameter: number
'availability/group/edit':
    directory: pages/user
    controller: AvailabilityPageController
    function: GroupAvailabilityEditPage
    parameter: number
'availability/member':
    directory: pages/user
    controller: AvailabilityPageController
    function: MemberAvailability


'calendar':
    directory: pages/user
    controller: CalendarPageController
    function: CalendarIndex


'finance':
    directory: pages/user
    controller: FinancePageController
    function: FinanceIndex
'finance/activate':
    directory: pages/user
    controller: FinancePageController
    function: LedgerActivation
'finance/closed':
    directory: pages/user
    controller: FinancePageController
    function: LedgerClosed


'member':
    directory: pages/user
    controller: SubordinatePageController
    function: SubordinateIndex
'member/committee':
    directory: pages/user
    controller: SubordinatePageController
    function: CommitteeDetails
    parameter: any


# **************************************************
# API - User Pages
# **************************************************
'action/request/committee':
    directory: api/user
    controller: RequestActionController
    function: GetCommittees
'action/request/committee/change':
    directory: api/user
    controller: RequestActionController
    function: RequestCommittee


'action/task/view':
    directory: api/user
    controller: TaskActionController
    function: GetViewTaskPageDetails
'action/task/view/details':
    directory: api/user
    controller: TaskActionController
    function: GetViewTaskDetailsPageDetails
    parameter: number
'action/task/view/details/(:num)/comment/add':
    directory: api/user
    controller: TaskActionController
    function: AddTaskComment
    parent: number
'action/task/view/details/(:num)/delete':
    directory: api/user
    controller: TaskActionController
    function: DeleteTask
    parent: number
'action/task/view/details/(:num)/submit':
    directory: api/user
    controller: TaskActionController
    function: SubmitTask
    parent: number
'action/task/add':
    directory: api/user
    controller: TaskActionController
    function: GetAddTaskPageDetails
'action/task/add-task':
    directory: api/user
    controller: TaskActionController
    function: AddTask


'action/availability':
    directory: api/user
    controller: AvailabilityActionController
    function: GetAvailability
'action/availability/update':
    directory: api/user
    controller: AvailabilityActionController
    function: UpdateAvailability
'action/availability/committee':
    directory: api/user
    controller: AvailabilityActionController
    function: GetCommitteeAvailability
'action/availability/group':
    directory: api/user
    controller: AvailabilityActionController
    function: GetAvailabilityGroupDetails
'action/availability/group/add':
    directory: api/user
    controller: AvailabilityActionController
    function: AddAvailabilityGroup
'action/availability/group/delete':
    directory: api/user
    controller: AvailabilityActionController
    function: DeleteAvailabilityGroup
'action/availability/group/view':
    directory: api/user
    controller: AvailabilityActionController
    function: GetViewAvailabilityGroupDetails
    parameter: number
'action/availability/group/edit':
    directory: api/user
    controller: AvailabilityActionController
    function: GetEditAvailabilityGroupDetails
    parameter: number
'action/availability/group/edit/(:num)/add':
    directory: api/user
    controller: AvailabilityActionController
    function: AddAvailabilityGroupMember
    parent: number
'action/availability/group/edit/(:num)/delete':
    directory: api/user
    controller: AvailabilityActionController
    function: DeleteAvailabilityGroupMember
    parent: number
'action/availability/member':
    directory: api/user
    controller: AvailabilityActionController
    function: GetMemberAvailability


'action/finance':
    directory: api/user
    controller: FinanceActionController
    function: GetFinancePageDetails
'action/finance/add':
    directory: api/user
    controller: FinanceActionController
    function: AddLedgerEntry
'action/finance/verify':
    directory: api/user
    controller: FinanceActionController
    function: VerifyLedgerEntry
    parameter: number
'action/finance/close':
    directory: api/user
    controller: FinanceActionController
    function: CloseLedger
'action/finance/activation':
    directory: api/user
    controller: FinanceActionController
    function: GetFinanceActivationDetails
'action/finance/activate':
    directory: api/user
    controller: FinanceActionController
    function: ActivateLedger
'action/finance/closed':
    directory: api/user
    controller: FinanceActionController
    function: GetClosedLedgerDetails


'action/member':
    directory: api/user
    controller: SubordinateActionController
    function: GetBatchDetails
'action/member/add':
    directory: api/user
    controller: SubordinateActionController
    function: AddMemberToBatch
'action/member/remove':
    directory: api/user
    controller:  SubordinateActionController
    function: RemoveMemberFromBatch
'action/member/committee':
    directory: api/user
    controller: SubordinateActionController
    function: GetCommitteeDetails
    parameter: any
'action/member/committee/add':
    directory: api/user
    controller: SubordinateActionController
    function: AddMemberToCommittee
    parameter: any
'action/member/committee/remove':
    directory: api/user
    controller: SubordinateActionController
    function: RemoveMemberFromCommittee
    parameter: any
'action/member/committee/make-committee-head':
    directory: api/user
    controller: SubordinateActionController
    function: AssignCommitteeHead
    parameter: any
'action/member/committee/frontman/modify':
    directory: api/user
    controller: SubordinateActionController
    function: ModifyFrontman

