'index':
    controller: IndexController

# **************************************************
# Pages - Public pages
# **************************************************
'login':
    directory: pages/public
    controller: LoggedOutPagesController
    function: Login
'sign-up':
    directory: pages/public
    controller: LoggedOutPagesController
    function: Signup

# **************************************************
# API - Public pages
# **************************************************
'action/login':
    directory: api/public
    controller: LoggedOutActionController
    function: Login
'action/logout':
    directory: api/public
    controller: LoggedOutActionController
    function: Logout
'action/signup':
    directory: api/public
    controller: LoggedOutActionController
    function: Signup


# **************************************************
# Pages - Admin pages
# **************************************************
'admin':
    directory: pages/admin
    controller: AdminPageController
    function: Home
'admin/login':
    directory: pages/admin
    controller: AdminPageController
    function: Login
'admin/account/password':
    directory: pages/admin
    controller: AdminPageController
    function: ChangePassword

'admin/batch':
    directory: pages/admin
    controller: BatchPageController
    function: Batch
'admin/batch/details':
    directory: pages/admin
    controller: BatchPageController
    function: BatchDetails
    parameter: number
'admin/batch/details/(:num)':
    directory: pages/admin
    controller: BatchPageController
    function: BatchCommitteeDetails
    parent: number
    parameter: any

'admin/member':
    directory: pages/admin
    controller: MemberPageController
    function: Member
'admin/member/details/':
    directory: pages/admin
    controller: MemberPageController
    function: MemberDetails
    parameter: number


# **************************************************
# API - Admin pages
# **************************************************
'action/admin/login':
    directory: api/admin
    controller: AdminActionController
    function: Login
'action/admin/logout':
    directory: api/admin
    controller: AdminActionController
    function: Logout
'action/admin/account/password/change':
    directory: api/admin
    controller: AdminActionController
    function: ChangePassword

'action/admin/batch':
    directory: api/admin
    controller: BatchActionController
    function: GetBatches
'action/admin/batch/add':
    directory: api/admin
    controller: BatchActionController
    function: AddBatch
'action/admin/batch/activate':
    directory: api/admin
    controller: BatchActionController
    function: ActivateBatch
'action/admin/batch/delete':
    directory: api/admin
    controller: BatchActionController
    function: DeleteBatch
'action/admin/batch/details':
    directory: api/admin
    controller: BatchActionController
    function: GetBatchDetails
    parameter: number
'action/admin/batch/details/add':
    directory: api/admin
    controller: BatchActionController
    function: AddBatchMember
    parameter: number
'action/admin/batch/details/remove':
    directory: api/admin
    controller: BatchActionController
    function: RemoveMemberFromBatch
    parameter: number
'action/admin/batch/details/(:num)':
    directory: api/admin
    controller: BatchActionController
    function: GetBatchCommitteeDetails
    parent: number
    parameter: any
'action/admin/batch/details/(:num)/modify/frontman':
    directory: api/admin
    controller: BatchActionController
    function: ModifyFrontmen
    parent: number
'action/admin/batch/details/(:num)/add/member/':
    directory: api/admin
    controller: BatchActionController
    function: AddBatchCommitteeMember
    parent: number
    parameter: any
'action/admin/batch/details/(:num)/remove/member/':
    directory: api/admin
    controller: BatchActionController
    function: RemoveBatchCommitteeMember
    parent: number
    parameter: any
'action/admin/batch/details/(:num)/make-committee-head/':
    directory: api/admin
    controller: BatchActionController
    function: UpdateBatchCommitteeHead
    parent: number
    parameter: any

'action/admin/member':
    directory: api/admin
    controller: MemberActionController
    function: GetMembers
'action/admin/member/delete':
    directory: api/admin
    controller: MemberActionController
    function: DeleteMember
'action/admin/member/details':
    directory: api/admin
    controller: MemberActionController
    function: GetMemberDetails
    parameter: number
'action/admin/member/details/modify':
    directory: api/admin
    controller: MemberActionController
    function: ModifyMemberDetails
    parameter: number

# **************************************************
# Pages - User pages
# **************************************************
'home':
    directory: pages
    controller: UserPagesController
    function: Home
'task-manager':
    directory: pages
    controller: UserPagesController
    function: TaskManager
'availability-tracker':
    directory: pages
    controller: UserPagesController
    function: AvailabilityTracker
'calendar':
    directory: pages
    controller: UserPagesController
    function: Calendar
'finance-tracker':
    directory: pages
    controller: UserPagesController
    function: FinanceTracker


# **************************************************
# API - Task Manager Pages
# **************************************************
'action/task-manager/add-task':
    directory: api
    controller: TaskManagerActionController
    function: AddTask
'action/task-manager/submit-task':
    directory: api
    controller: TaskManagerActionController
    function: SubmitTask

# **************************************************
# Pages - Task Manager Pages
# **************************************************
'task-manager/full-task':
    directory: pages
    controller: TaskManagerController
    function: FullTask

# **************************************************
# API - Finance Tracker Pages
# **************************************************
'action/finance-tracker/add-debit-credit':
    directory: api
    controller: FinanceTrackerActionController
    function: AddDebitCredit
'action/finance-tracker/verify-balance':
    directory: api
    controller: FinanceTrackerActionController
    function: VerifyBalance
'action/finance-tracker/approve-statement':
    directory: api
    controller: FinanceTrackerActionController
    function: ApproveStatement

# **************************************************
# Pages - Finance Tracker Pages
# **************************************************
'finance-tracker/generate-statement':
    directory: pages
    controller: FinanceTrackerController
    function: GenerateStatement

# **************************************************
# API - Availability Tracker Pages
# **************************************************
'action/availability-tracker/update-schedule':
    directory: api
    controller: AvailabilityTrackerActionController
    function: UpdateSchedule
'action/availability-tracker/delete-group':
    directory: api
    controller: AvailabilityTrackerActionController
    function: DeleteGroup
'action/availability-tracker/create-new-group':
    directory: api
    controller: AvailabilityTrackerActionController
    function: CreateNewGroup

# **************************************************
# Pages - Availability Tracker Pages
# **************************************************
'availability-tracker/add-custom-group':
    directory: pages
    controller: AvailabilityTrackerController
    function: AddCustomGroup

# **************************************************
# API - Calendar Pages
# **************************************************
'action/calendar/add-event':
    directory: api
    controller: CalendarActionController
    function: AddEvent