'index':
    controller: IndexController

# **************************************************
# Pages - Public pages
# **************************************************
'login':
    directory: pages
    controller: PublicPagesController
    function: Login
'sign-up':
    directory: pages
    controller: PublicPagesController
    function: Signup

# **************************************************
# API - Public pages
# **************************************************
'action/login':
    directory: api
    controller: PublicPagesActionController
    function: Login
'action/logout':
    directory: api
    controller: PublicPagesActionController
    function: Logout
'action/signup':
    directory: api
    controller: PublicPagesActionController
    function: Signup


# **************************************************
# Pages - Admin pages
# **************************************************
'admin/home':
    directory: pages
    controller: SystemAdministratorController
    function: Home
'admin/login':
    directory: pages
    controller: SystemAdministratorController
    function: Access
'admin/change-password':
    directory: pages
    controller: SystemAdministratorController
    function: EditPassword
'admin/manage/batch':
    directory: pages
    controller: SystemAdministratorController
    function: ManageBatch

# **************************************************
# API - Admin pages
# **************************************************
'action/admin/access':
    directory: api
    controller: SystemAdministratorActionController
    function: Login
'action/admin/change-password':
    directory: api
    controller: SystemAdministratorActionController
    function: UpdatePassword
'action/admin/display-batches':
    directory: api
    controller: SystemAdministratorActionController
    function: GetBatches
'action/admin/add-batch':
    directory: api
    controller: SystemAdministratorActionController
    function: CreateBatch
'action/admin/delete-batch':
    directory: api
    controller: SystemAdministratorActionController
    function: DeleteBatch


# **************************************************
# Pages - User pages
# **************************************************
'home':
    directory: pages
    controller: UserPagesController
    function: Home
'task-manager':
    directory: pages
    controller: UserPagesController
    function: TaskManager
'availability-tracker':
    directory: pages
    controller: UserPagesController
    function: AvailabilityTracker
'calendar':
    directory: pages
    controller: UserPagesController
    function: Calendar
'finance-tracker':
    directory: pages
    controller: UserPagesController
    function: FinanceTracker


# **************************************************
# API - Task Manager Pages
# **************************************************
'action/task-manager/add-task':
    directory: api
    controller: TaskManagerActionController
    function: AddTask
'action/task-manager/submit-task':
    directory: api
    controller: TaskManagerActionController
    function: SubmitTask

# **************************************************
# Pages - Task Manager Pages
# **************************************************
'task-manager/full-task':
    directory: pages
    controller: TaskManagerController
    function: FullTask

# **************************************************
# API - Finance Tracker Pages
# **************************************************
'action/finance-tracker/add-debit-credit':
    directory: api
    controller: FinanceTrackerActionController
    function: AddDebitCredit
'action/finance-tracker/verify-balance':
    directory: api
    controller: FinanceTrackerActionController
    function: VerifyBalance
'action/finance-tracker/approve-statement':
    directory: api
    controller: FinanceTrackerActionController
    function: ApproveStatement

# **************************************************
# Pages - Finance Tracker Pages
# **************************************************
'finance-tracker/generate-statement':
    directory: pages
    controller: FinanceTrackerController
    function: GenerateStatement

# **************************************************
# API - Availability Tracker Pages
# **************************************************
'action/availability-tracker/update-schedule':
    directory: api
    controller: AvailabilityTrackerActionController
    function: UpdateSchedule
'action/availability-tracker/delete-group':
    directory: api
    controller: AvailabilityTrackerActionController
    function: DeleteGroup
'action/availability-tracker/create-new-group':
    directory: api
    controller: AvailabilityTrackerActionController
    function: CreateNewGroup

# **************************************************
# Pages - Availability Tracker Pages
# **************************************************
'availability-tracker/add-custom-group':
    directory: pages
    controller: AvailabilityTrackerController
    function: AddCustomGroup

# **************************************************
# API - Calendar Pages
# **************************************************
'action/calendar/add-event':
    directory: api
    controller: CalendarActionController
    function: AddEvent